[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "python manage.py migrate --noinput --settings=config.settings.railway && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --log-level debug"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
